### ISSUE TITLE
Rewrite with KSP

### ISSUE THREAD

**Issue by klamborowski** [FutureMind/koru#13]
Add support for [KSP](https://github.com/google/ksp). Based on [recent article](https://android-developers.googleblog.com/2021/02/announcing-kotlin-symbol-processing-ksp.html) it could speed up build time 2x in compare to KAPT.

After doing that you can also add library to [Supported Libraries](https://github.com/google/ksp#supported-libraries) section.

**Comment by micHar** [comment]
I was already looking into this and decided that I'm gonna wait a bit until it's field tested by bigger guys like moshi. Will keep the issue open, though.

**Comment by micHar** [comment]
The rewrite is almost done, there are some minor issues with kotlinpoet / typealiases. The processor will be still available for kapt for a few releases.
