### ISSUE TITLE
MainScopeProvider needs to be strictly named MainScopeProvider

### ISSUE THREAD

**Issue by 837** [FutureMind/koru#28]
If you name the MainScopeProvider class anything else, the generated classes will put null for the scope. Even when declared correctly in the Annotation

**Comment by micHar** [comment]
Hmmm, maybe a regression? I'm pretty sure I have some other name for scope provider somewhere. Can you show the code where you declare the scope provider and then where you attach it to a wrapped class with launchOnScope?

**Comment by 837** [comment]
tried it again in a simpler setup, seems to work. I'll close it and keep my eyes open if I can reproduce it again.
