### ISSUE TITLE
Include (or link to) sample app

### ISSUE THREAD

**Issue by ankushg** [FutureMind/koru#6]
It would be great if you could include a sample app that uses all of the features of this utility.

Would help with documentation since you can point to real usages, and it could serve as a full integration test as well.

**Comment by micHar** [comment]
Absolutely!
I will probably not include the whole example here, because kmm projects are very verbose - a shared module, an android module and ios app dir. Instead I'm planning to post a separate repo but I want to write a corresponding article as well. Just need a bit of time for that.

**Comment by ankushg** [comment]
Makes sense -- I knew it must be in the pipeline somewhere, just wanted to file an issue so I could follow it and check it out once it's published 😉

**Comment by micHar** [comment]
Here it is: [introductory article](https://medium.com/futuremind/handling-kotlin-multiplatform-coroutines-in-swift-koru-4a80b93f232b) and [example repo](https://github.com/FutureMind/koru-example). Enjoy :)
